# Generated by Django 4.0 on 2022-12-06 19:26

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100000)),
                ('type', models.CharField(blank=True, choices=[('Setup Data', 'Setup Data'), ('Calibration Data', 'Calibration Data')], default='yes', max_length=100000)),
                ('image', models.ImageField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='assets/images'), upload_to='')),
                ('description', models.CharField(blank=True, max_length=1000000)),
                ('version', models.CharField(blank=True, default='yes', max_length=1000)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
