# Generated by Django 4.0 on 2022-12-06 19:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_data',
            options={'ordering': ('id',), 'verbose_name': 'Model Data Source'},
        ),
        migrations.AlterField(
            model_name='model_data',
            name='description',
            field=models.TextField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='model_data',
            name='image',
            field=models.ImageField(default=None, storage=django.core.files.storage.FileSystemStorage(location='assets/images'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='model_data',
            name='name',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='model_data',
            name='type',
            field=models.CharField(choices=[('Setup Data', 'Setup Data'), ('Calibration Data', 'Calibration Data')], default='Setup Data', max_length=100000),
        ),
        migrations.AlterField(
            model_name='model_data',
            name='version',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
