# Generated by Django 4.1.4 on 2022-12-28 21:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100000)),
                ('image', models.ImageField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='assets/images'), upload_to='')),
            ],
            options={
                'verbose_name': 'About CoSWAT-GM',
                'ordering': ('id',),
            },
        ),
    ]
