# Generated by Django 4.1.3 on 2023-01-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_location_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100000)),
                ('text', models.TextField(max_length=100000)),
            ],
            options={
                'verbose_name': 'Welcome Message',
                'ordering': ('id',),
            },
        ),
    ]
